name: Docker Compose Integration Test

on:
  push:
    branches:
      - ld
  pull_request:
    branches:
      - ld
  workflow_dispatch:

jobs:
  test-service:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15 # Adjust the sleep time as needed for your services to initialize

      - name: Run curl command to test the service
        run: |
          curl http://localhost:5000/collections/obs/items/964\?f\=jsonld | jq '.["@context"]'

      - name: Stop and clean up services
        if: always()
        run: docker compose down
